language: android
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - ANDROID_TOOLS=${ANDROID_HOME}/tools
  - secure: "Ly1fzDtwAuvEb90kjRBXa3j4iIwSqD4YlwDrJAr5ITlaRoIABiuhRrdVdNGkl+pO1LMOEeo9Y2gLO4KSy+ZRxpMf/h8djHpcsuhKAAw14kM0MX9H/wBjGklqWcxhaHGqhWDJcSJs4HkhjgPcFm28Evgz1aS1cgWlfgPvb0sVpf3v11SxsTfmCUCD0zuZXckPLRR7fhDWIhlmmTlwV/1Z8dxc5vb9O4+wDR2FLQ9qp+ENIxOudlFNf+R8qS2TnXzEeLzo+5Wvc9orwt3ftvEUdcJCICvRvfz3WXT7vFJu52QZBweUonR/mhevaiL7ILM7Rb33AYT63913+BzUlTKpTUN1RwYptn5jGesCTvNi9KQQccT5Tnq7JuVleE3q+VvItZkjJwH8e8aCjBEyPEJO+iyK01RvbKyWSlXQQRYWy4nZ3Zfaie0ibJEdHud9uBLBCc46s+R4Vj5+w2GioTuQ00wVe2Yb1eASicSU/GAx6n6oFQf1zOqPLSaCP1K9zGoRlcYxrLZZtkPPeTgMpA4mRa/WgiNsMjKbldQZ8xZEep+tSFyRTS0zB3aIc0tjww4GXRNOkldD66FM0uEd6oKCAAaCQvBTQl9fYS9HF2GlWbXt3xmuNtz8W060YNEUcxevj/cIPCrdngx3akl25ZygVolJ3WQFfgMVGa1MgkKOnSY="
  - secure: "YTxOZ5v1FHy3ATcjaKIY9Iq1Hq97AQsr8TKINpv67iuT7dZGOPVxQ2n+nUpq3Ulslp+eQ5vSmW5+NzfLPlj6jRh04tHn7/kEOK+onvKGzTsW++2CS/Oaodar896fX9L4Yx7VfPNSg1zzAh2X9llDj+J416K+YAuTosah6c1uB/Lkkm5RwCZw3cqzXauBHPcqsjkYqQpFnKCviKeKNfMn9pEXrKqm7fQGOt3v6o9E1viK5SWCkEbJ5VX+ufo0Cc7X307W1gjUsRjnj2BudyKwmWbKfiIwTPv/XHrx7oLyzGkL4wUdbzKKHphgLu0mseuxxrXONIMQhOM6U7Ig2PH/wuOsRjtDBw7wl62rdRx4Wo1nbFLF/84gYh8X+D9xnBeKm2HpFUQHp6z48X7AoFjykyTTPl5emmQnSy4JuxSpcXqvtKLIx4OJJonFSfbhMpx7BBmkEE+RKSFXR0J0Z97nfn5351ud29aTo2TgHptcqBqZbkgkHK8fg/LNcXjiEmeloMSQ9AmqMUOvGRiicUpxVKnmPMKxxnMDdR5lNGt5h+3MbxHoZOLJB84UOACujyEjkzCPgcaD4hrqI3BzkHHzzbo5+i5Ahgnb1fsn9Yqp1u+LV/JjW/KeBi3DV0rFYy+e4q4o7a8WA9wqScRCHlc+GbgFNds8Gar8BvhUJaOU4lU="
notifications:
  email: false
before_install:
- nvm install 7
- wget http://services.gradle.org/distributions/gradle-4.2.1-bin.zip
- unzip gradle-4.2.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-4.2.1
- export PATH=${GRADLE_HOME}/bin:${ANDROID_HOME}:${ANDROID_HOME}/emulator:${ANDROID_TOOLS}:${ANDROID_TOOLS}/bin:${ANDROID_HOME}/platform-tools:$PATH
- node --version
- gradle --version
- echo y | android update sdk -u --filter android-25
android:
  components:
  - tools
  - android-26
install:
- npm cache clean
- npm install
- npm install -g cordova
before_script:
- cordova platform rm android
- cordova platform add android@6.3.0
- echo "configurations.all {\nresolutionStrategy.force 'com.android.support:support-v4:26.0.0'\n}" >> platforms/android/build.gradle
script:
- cordova prepare
- cordova build android --release
release:
- exit 0
before_deploy:
- openssl aes-256-cbc -K $encrypted_9f95e6791251_key -iv $encrypted_9f95e6791251_iv -in keystore.jks.enc -out keystore.jks -d
- cd /home/travis/build/HubHouse-Lille/GeokH-app/platforms/android/build/outputs/apk
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${TRAVIS_BUILD_DIR}/keystore.jks
    -storepass $KEY_PASS -keypass $KEY_PASS android-release-unsigned.apk geokh
- jarsigner -verify android-release-unsigned.apk
- mv android-release-unsigned.apk geokh.apk
deploy:
  provider: releases
  api_key: $TOKEN
  file: geokh.apk
  skip_cleanup: true
  on:
    tags: true
