language: android

node_js:
  - 5.4

notifications:
  email: false

sudo: false

branches:
  only:
  - master
  - travis

before_install:
  - npm i -g npm@5.4.2

install:
  - npm cache clean
  - npm install
  - npm install -g cordova
  - echo y | android update sdk -u --filter android-25

before_script:
  - cordova platform rm android
  - cordova platform add android@6.2.3

script:
  - cordova prepare
  - cordova build android --release -- --ant

release:
  - exit 0